# Generated by Django 4.1 on 2022-10-11 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0004_alter_feedback_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='question',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='subject',
        ),
    ]
