# Generated by Django 4.1 on 2022-10-12 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0006_alter_question_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
