# Generated by Django 4.1 on 2022-10-13 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0007_alter_quiz_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(default='choose...', on_delete=django.db.models.deletion.CASCADE, to='HomePage.quiz'),
        ),
    ]
